### ISSUE TITLE
start coding

### ISSUE THREAD

**Issue by alinelena** [stfc/aiida-mlip#31]
Minimal features to be implemented:

- [x] single point calculations see and blocked by stfc/janus-core#10 
- [x] geometry optimisation see and blocked by stfc/janus-core#12 
- [x] data transfer see and blocked by stfc/aiida-mlip#78 

blocked by stfc/aiida-mlip#1 and stfc/aiida-mlip#10
